{
 "title": "Swarm services",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "hostname", "query": { "query": "label_values(hostname)" } },
   {
    "name": "service",
    "query": {
     "query": "label_values(container_label_com_docker_swarm_service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Task status",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (state) (swarm_manager_tasks_total{})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Task uptime",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${__to:date:seconds} - container_start_time_seconds{hostname=~\"$hostname\",container_label_com_docker_swarm_service_name=~\"$service\"}",
     "legendFormat": "{{ container_label_com_docker_swarm_service_name}}:{{ hostname }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (instance,hostname,container_label_com_docker_swarm_service_name) (irate(container_cpu_usage_seconds_total{hostname=~\"$hostname\",container_label_com_docker_swarm_service_name=~\"$service\"}[$__rate_interval]))) / on(instance) group_left(hostname) machine_cpu_cores{hostname=~\"$hostname\"}",
     "legendFormat": "{{ hostname }} - {{ container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{hostname=~\"$hostname\",container_label_com_docker_swarm_service_name=~\"$service\"}",
     "legendFormat": "{{ hostname }} - {{ container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Network bandwidth in",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (hostname,container_label_com_docker_swarm_service_name) (irate(container_network_receive_bytes_total{hostname=~\"$hostname\",container_label_com_docker_swarm_service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{ hostname }} - {{ container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Network bandwidth out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (hostname,container_label_com_docker_swarm_service_name) (irate(container_network_transmit_bytes_total{hostname=~\"$hostname\",container_label_com_docker_swarm_service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{ hostname }} - {{ container_label_com_docker_swarm_service_name}}"
    }
   ]
  }
 ]
}