{
 "title": "Swarm nodes",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "hostname", "query": { "query": "label_values(instance)" } },
   { "name": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Container status count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{}",
     "legendFormat": "{{ instance }} - {{ state }}"
    }
   ]
  },
  {
   "title": "Container status count over time",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{}",
     "legendFormat": "{{ instance }} - {{ state }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}-node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} "
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} total"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}-node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} "
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} total"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",instance=~\"$instance\"}-node_filesystem_free_bytes{mountpoint=\"/\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} total"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",instance=~\"$instance\"}-node_filesystem_free_bytes{mountpoint=\"/\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} total"
    }
   ]
  },
  {
   "title": "Bandwidth usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"eth0\",instance=~\"$instance\"}[1$__rate_interval])",
     "legendFormat": "{{ instance }} Download"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total{device=\"eth0\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} Upload"
    }
   ]
  }
 ]
}